<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Cheetah.AspNetCore\Cheetah.AspNetCore.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.AspNetCore.Contracts\Cheetah.AspNetCore.Contracts.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Backend.Endpoints\Cheetah.Backend.Endpoints.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Core\Cheetah.Core.csproj"/>
        <ProjectReference Include="..\..\..\Cheetah.Mapping.Core\Cheetah.Mapping.Core.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Mapping.Mapster\Cheetah.Mapping.Mapster.csproj" />
        <ProjectReference Include="..\Cheetah.Admin.Modules.Clients.Application\Cheetah.Admin.Modules.Clients.Application.csproj" />
        <ProjectReference Include="..\Cheetah.Admin.Modules.Clients.DataAccess\Cheetah.Admin.Modules.Clients.DataAccess.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer"/>
        <ProjectReference Include="..\..\..\Cheetah.Generators.Endpoints\Cheetah.Generators.Endpoints.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer"/>
    </ItemGroup>

</Project>
