<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Cheetah.Contracts\Cheetah.Contracts.csproj" />
      <ProjectReference Include="..\..\..\Cheetah.Core\Cheetah.Core.csproj" />
      <ProjectReference Include="..\Crm.MasterData.Domain\Crm.MasterData.Domain.csproj" />
      <ProjectReference Include="..\..\..\Cheetah.Generators.Common\Cheetah.Generators.Common.csproj"
                        ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    </ItemGroup>

</Project>
