<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\Cheetah.Core\Cheetah.Core.csproj" />
        <ProjectReference Include="..\Cheetah.Expressions.JsonLogic\Cheetah.Expressions.JsonLogic.csproj" />
        <ProjectReference Include="..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

</Project>
