<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.Options" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="MongoDB.Driver" />
        <PackageReference Include="Shouldly" />
        <PackageReference Include="Testcontainers.MongoDb" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Cheetah.Core.Mongo\Cheetah.Core.Mongo.csproj" />
        <ProjectReference Include="..\Cheetah.Core.Outbox.Mongo\Cheetah.Core.Outbox.Mongo.csproj" />
        <ProjectReference Include="..\Cheetah.Core.Inbox.Mongo\Cheetah.Core.Inbox.Mongo.csproj" />
        <ProjectReference Include="..\Cheetah.Saga.Mongo\Cheetah.Saga.Mongo.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

</Project>
