<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(MsPackageVersion)" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="$(MsPackageVersion)" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="$(MsPackageVersion)" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Cheetah.Core.EntityFramework\Cheetah.Core.EntityFramework.csproj" />
      <ProjectReference Include="..\Cheetah.Core.Events\Cheetah.Core.Events.csproj" />
      <ProjectReference Include="..\Cheetah.Core.Tenants\Cheetah.Core.Tenants.csproj" />
      <ProjectReference Include="..\Cheetah.Core\Cheetah.Core.csproj" />
    </ItemGroup>

</Project>
