<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(MsPackageVersion)" />
    </ItemGroup>

    <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Cheetah.Core.EntityFramework\Cheetah.Core.EntityFramework.csproj" />
      <ProjectReference Include="..\Cheetah.Core.Events\Cheetah.Core.Events.csproj" />
      <ProjectReference Include="..\Cheetah.Core.Tenants\Cheetah.Core.Tenants.csproj" />
      <ProjectReference Include="..\Cheetah.Core\Cheetah.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer"/>
    </ItemGroup>

</Project>
