<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
        <PackageReference Include="Cheetah.Modules.Identity.Api" />
        <PackageReference Include="Cheetah.ServiceDefaults" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\AppName.Identity.Application\AppName.Identity.Application.csproj" />
        <ProjectReference Include="..\AppName.Identity.DataAccess\AppName.Identity.DataAccess.csproj" />
        <ProjectReference Include="..\AppName.Identity.Domain\AppName.Identity.Domain.csproj" />
    </ItemGroup>

    <ItemGroup Label="Source Generators">
        <PackageReference Include="Cheetah.Generators.Module">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Cheetah.Generators.Application">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Cheetah.Generators.Endpoints">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
