<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
    </PropertyGroup>

    <ItemGroup Label="Cheetah Framework">
        <PackageVersion Include="Cheetah.AspNetCore" Version="__CheetahVersion__" />
        <PackageVersion Include="Cheetah.AspNetCore.Contracts" Version="__CheetahVersion__" />
        <PackageVersion Include="Cheetah.Backend.CQRS" Version="__CheetahVersion__" />
        <PackageVersion Include="Cheetah.Backend.Endpoints" Version="__CheetahVersion__" />
<!--#if (eventBus == "redis")-->
        <PackageVersion Include="Cheetah.Backend.Events.Redis" Version="__CheetahVersion__" />
<!--#else-->
        <PackageVersion Include="Cheetah.Backend.Events.InMemory" Version="__CheetahVersion__" />
<!--#endif-->
        <PackageVersion Include="Cheetah.Backend.Jwt" Version="__CheetahVersion__" />
        <PackageVersion Include="Cheetah.Contracts" Version="__CheetahVersion__" />
        <PackageVersion Include="Cheetah.Core" Version="__CheetahVersion__" />
        <PackageVersion Include="Cheetah.Core.CQRS" Version="__CheetahVersion__" />
        <PackageVersion Include="Cheetah.Core.Domain" Version="__CheetahVersion__" />
<!--#if (databaseType == "postgres")-->
        <PackageVersion Include="Cheetah.Core.EntityFramework.PostgreSql" Version="__CheetahVersion__" />
<!--#else-->
        <PackageVersion Include="Cheetah.Core.EntityFramework.MsSql" Version="__CheetahVersion__" />
<!--#endif-->
        <PackageVersion Include="Cheetah.Core.Events" Version="__CheetahVersion__" />
        <PackageVersion Include="Cheetah.Core.Grid" Version="__CheetahVersion__" />
        <PackageVersion Include="Cheetah.Core.Identity.DataAccess" Version="__CheetahVersion__" />
        <PackageVersion Include="Cheetah.Core.Identity.Domain" Version="__CheetahVersion__" />
        <PackageVersion Include="Cheetah.CQRS.Dispatcher" Version="__CheetahVersion__" />
        <PackageVersion Include="Cheetah.Generators.Application" Version="__CheetahVersion__" />
        <PackageVersion Include="Cheetah.Generators.Endpoints" Version="__CheetahVersion__" />
        <PackageVersion Include="Cheetah.Generators.Module" Version="__CheetahVersion__" />
        <PackageVersion Include="Cheetah.Mapping.Core" Version="__CheetahVersion__" />
        <PackageVersion Include="Cheetah.Mapping.Mapster" Version="__CheetahVersion__" />
        <PackageVersion Include="Cheetah.Modules.Identity.Api" Version="__CheetahVersion__" />
        <PackageVersion Include="Cheetah.Modules.Identity.Application" Version="__CheetahVersion__" />
        <PackageVersion Include="Cheetah.Modules.Identity.Contracts" Version="__CheetahVersion__" />
        <PackageVersion Include="Cheetah.Modules.Identity.DataAccess" Version="__CheetahVersion__" />
        <PackageVersion Include="Cheetah.Modules.Identity.Domain" Version="__CheetahVersion__" />
        <PackageVersion Include="Cheetah.Modules.Identity.DomainEvents" Version="__CheetahVersion__" />
        <PackageVersion Include="Cheetah.OpenApi" Version="__CheetahVersion__" />
        <PackageVersion Include="Cheetah.Scalar" Version="__CheetahVersion__" />
        <PackageVersion Include="Cheetah.ServiceDefaults" Version="__CheetahVersion__" />
    </ItemGroup>

    <ItemGroup Label="Microsoft">
        <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.3" />
        <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
        <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3" />
        <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.3" />
        <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.3.0" />
        <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="10.3.0" />
<!--#if (databaseType == "postgres")-->
        <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
<!--#else-->
        <PackageVersion Include="Microsoft.Data.SqlClient" Version="6.0.2" />
        <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.3" />
<!--#endif-->
        <PackageVersion Include="StackExchange.Redis" Version="2.11.0" />
    </ItemGroup>

    <ItemGroup Label="Testing">
        <PackageVersion Include="coverlet.collector" Version="8.0.0" />
        <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.3" />
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
        <PackageVersion Include="Moq" Version="4.20.72" />
        <PackageVersion Include="Shouldly" Version="4.3.0" />
        <PackageVersion Include="Testcontainers.PostgreSql" Version="4.10.0" />
        <PackageVersion Include="xunit" Version="2.9.3" />
        <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    </ItemGroup>
</Project>
