<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\..\Cheetah.Contracts\Cheetah.Contracts.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Core\Cheetah.Core.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Core.Events\Cheetah.Core.Events.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Workflow\Cheetah.Workflow.csproj" />
        <ProjectReference Include="..\Cheetah.Modules.Workflow.Shared\Cheetah.Modules.Workflow.Shared.csproj" />
    </ItemGroup>

</Project>
