<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\..\..\Cheetah.Core\Cheetah.Core.csproj" />
      <ProjectReference Include="..\..\..\Cheetah.Mapping.Core\Cheetah.Mapping.Core.csproj" />
      <ProjectReference Include="..\Cheetah.Modules.SalesDocuments.Application\Cheetah.Modules.SalesDocuments.Application.csproj" />
      <ProjectReference Include="..\Cheetah.Modules.SalesDocuments.Contracts\Cheetah.Modules.SalesDocuments.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Cheetah.Mapping.Generators\Cheetah.Mapping.Generators.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    </ItemGroup>

</Project>
