<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Cheetah.Features.Contracts\Cheetah.Features.Contracts.csproj" />
    <ProjectReference Include="..\Cheetah.Features.Shared\Cheetah.Features.Shared.csproj" />
    <ProjectReference Include="..\..\Cheetah.Frontend.CQRS\Cheetah.Frontend.CQRS.csproj" />
    <ProjectReference Include="..\..\Cheetah.Core\Cheetah.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" Version="$(MsPackageVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
  </ItemGroup>

</Project>
