<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\Cheetah.Core\Cheetah.Core.csproj" />
        <ProjectReference Include="..\Cheetah.Core.Mongo\Cheetah.Core.Mongo.csproj" />
        <ProjectReference Include="..\Cheetah.Core.Outbox\Cheetah.Core.Outbox.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MongoDB.Driver" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Options" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    </ItemGroup>

</Project>
