<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Cheetah.Core\Cheetah.Core.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Core.CQRS\Cheetah.Core.CQRS.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Core.DataAccess\Cheetah.Core.DataAccess.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Core.Events\Cheetah.Core.Events.csproj" />
        <ProjectReference Include="..\Cheetah.Modules.Notification.Domain\Cheetah.Modules.Notification.Domain.csproj" />
        <ProjectReference Include="..\Cheetah.Modules.Notification.Contracts\Cheetah.Modules.Notification.Contracts.csproj" />
        <ProjectReference Include="..\Cheetah.Modules.Notification.DomainEvents\Cheetah.Modules.Notification.DomainEvents.csproj" />
        <ProjectReference Include="..\..\Email\Cheetah.Modules.Email.DomainEvents\Cheetah.Modules.Email.DomainEvents.csproj" />
        <ProjectReference Include="..\..\Identity\Cheetah.Modules.Identity.DomainEvents\Cheetah.Modules.Identity.DomainEvents.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    </ItemGroup>

</Project>
