<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <ProjectReference Include="..\..\..\Cheetah.Core\Cheetah.Core.csproj"/>
        <ProjectReference Include="..\..\..\Cheetah.Mapping.Mapster\Cheetah.Mapping.Mapster.csproj"/>
        <ProjectReference Include="..\Cheetah.Modules.Deals.Application\Cheetah.Modules.Deals.Application.csproj" />
        <ProjectReference Include="..\Cheetah.Modules.Deals.Contracts\Cheetah.Modules.Deals.Contracts.csproj" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    </ItemGroup>
</Project>
