<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>12.0</LangVersion>
        <Nullable>enable</Nullable>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <IsRoslynComponent>true</IsRoslynComponent>
        <!-- Analyzer packaging -->
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <DevelopmentDependency>true</DevelopmentDependency>
        <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <None Include="$(OutputPath)\$(AssemblyName).dll"
              Pack="true"
              PackagePath="analyzers/dotnet/cs"
              Condition="Exists('$(OutputPath)\$(AssemblyName).dll')" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\Cheetah.Generators.Core\IsExternalInit.cs">
            <Link>IsExternalInit.cs</Link>
        </Compile>
        <Compile Include="..\Cheetah.Core\Modularity\ICrmModule.cs">
            <Link>Common\ICrmModule.cs</Link>
        </Compile>
        <Compile Include="..\Cheetah.Core\ApplicationInitializationContext.cs">
            <Link>Common\ApplicationInitializationContext.cs</Link>
        </Compile>
        <Compile Include="..\Cheetah.Core\Modularity\ServiceConfigurationContext.cs">
            <Link>Common\ServiceConfigurationContext.cs</Link>
        </Compile>
        <Compile Include="..\Cheetah.Core\DependencyInjection\IServiceProviderAccessor.cs">
            <Link>Common\IServiceProviderAccessor.cs</Link>
        </Compile>
        <Compile Include="..\Cheetah.Core\Extensions\Collections\DictionaryExtensions.cs">
            <Link>Common\DictionaryExtensions.cs</Link>
        </Compile>
    </ItemGroup>

</Project>
