<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\Cheetah.Core.DataAccess\Cheetah.Core.DataAccess.csproj" />
        <ProjectReference Include="..\Cheetah.Core.Domain\Cheetah.Core.Domain.csproj" />
        <ProjectReference Include="..\Cheetah.Core.Specification\Cheetah.Core.Specification.csproj" />
        <ProjectReference Include="..\Cheetah.Core\Cheetah.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MongoDB.Driver" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Options" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    </ItemGroup>

</Project>
