<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Cheetah.Core\Cheetah.Core.csproj" />
    <ProjectReference Include="..\..\Cheetah.Core.Tenants\Cheetah.Core.Tenants.csproj" />
    <ProjectReference Include="..\..\Cheetah.Core.CQRS\Cheetah.Core.CQRS.csproj" />
    <ProjectReference Include="..\..\Cheetah.Core.Events\Cheetah.Core.Events.csproj" />
    <ProjectReference Include="..\..\Cheetah.Core.Domain\Cheetah.Core.Domain.csproj" />
    <ProjectReference Include="..\..\Cheetah.Core.EntityFramework.Tenants\Cheetah.Core.EntityFramework.Tenants.csproj" />
    <ProjectReference Include="..\..\Cheetah.Tenants\Cheetah.Tenants.Events\Cheetah.Tenants.Events.csproj" />
    <ProjectReference Include="..\..\Cheetah.Tenants\Cheetah.Tenants.Client\Cheetah.Tenants.Client.csproj" />
    <ProjectReference Include="..\Cheetah.Identity.Domain\Cheetah.Identity.Domain.csproj" />
    <ProjectReference Include="..\Cheetah.Identity.Events\Cheetah.Identity.Events.csproj" />
    <ProjectReference Include="..\Cheetah.Identity.Shared\Cheetah.Identity.Shared.csproj" />
    <ProjectReference Include="..\Cheetah.Identity.DataAccess\Cheetah.Identity.DataAccess.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(MsPackageVersion)" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
  </ItemGroup>

</Project>
