<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <SupportedPlatform Include="browser"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\Cheetah.Core\Cheetah.Core.csproj"/>
        <ProjectReference Include="..\..\..\..\Cheetah.Blazor.Components\Cheetah.Blazor.Components.csproj"/>
        <ProjectReference Include="..\..\..\..\Cheetah.Frontend.Navigation\Cheetah.Frontend.Navigation.csproj"/>
        <ProjectReference Include="..\..\..\..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer"/>
        <ProjectReference Include="..\Crm.Candidates.ApiClient\Crm.Candidates.ApiClient.csproj"/>
        <ProjectReference Include="..\Crm.Candidates.Contracts\Crm.Candidates.Contracts.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Components\"/>
        <Folder Include="wwwroot\"/>
    </ItemGroup>

</Project>
