<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\..\Cheetah.Core\Cheetah.Core.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Core.Events\Cheetah.Core.Events.csproj" />
        <ProjectReference Include="..\Cheetah.Modules.Identity.DomainEvents\Cheetah.Modules.Identity.DomainEvents.csproj" />
    </ItemGroup>

</Project>
