<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Cheetah.Tenants.Domain\Cheetah.Tenants.Domain.csproj" />
    <ProjectReference Include="..\Cheetah.Tenants.Shared\Cheetah.Tenants.Shared.csproj" />
    <ProjectReference Include="..\..\Cheetah.Core.EntityFramework.Tenants\Cheetah.Core.EntityFramework.Tenants.csproj" />
    <ProjectReference Include="..\..\Cheetah.Core.EntityFramework\Cheetah.Core.EntityFramework.csproj" />
    <ProjectReference Include="..\..\Cheetah.Core.DataAccess\Cheetah.Core.DataAccess.csproj" />
    <ProjectReference Include="..\..\Cheetah.Core\Cheetah.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(MsPackageVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="$(MsPackageVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="$(MsPackageVersion)">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    <ProjectReference Include="..\..\Cheetah.Core.EntityFramework.PostgreSql\Cheetah.Core.EntityFramework.PostgreSql.csproj" />
  </ItemGroup>

</Project>
