<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsAspireHost>true</IsAspireHost>
        <UserSecretsId>6534cdf0-f504-44c4-8e91-4a13729613f6</UserSecretsId>
        <NoWarn>$(NoWarn);ASPIRE004</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost" />
        <PackageReference Include="Aspire.Hosting.PostgreSQL" />
        <PackageReference Include="Aspire.Hosting.Redis"  />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Modules\Admin\Cheetah.Admin.Api\Cheetah.Admin.Api.csproj" />
        <ProjectReference Include="..\Modules\Admin\Cheetah.Admin.Client\Cheetah.Admin.Client.csproj" />
        <ProjectReference Include="..\Modules\Candidates\Candidates\Crm.Candidates.Api\Crm.Candidates.Api.csproj" />
        <ProjectReference Include="..\Modules\Crm.Proxy\Crm.Proxy.csproj" />
        <ProjectReference Include="..\Modules\Features\Crm.Features.Api\Crm.Features.Api.csproj" />
        <ProjectReference Include="..\Modules\Recruitment\Crm.Recruitment.Api\Crm.Recruitment.Api.csproj" />
        <ProjectReference Include="..\Modules\Recruitment\Crm.Recruitment.Client\Crm.Recruitment.Client.csproj" />
        <ProjectReference Include="..\Modules\VacancyTasks\VacancyTasks\Crm.VacancyTasks.Api\Crm.VacancyTasks.Api.csproj" />
    </ItemGroup>

</Project>
