<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <SupportedPlatform Include="browser"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Authorization"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web"/>
        <PackageReference Include="Microsoft.Extensions.Http"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Cheetah.Blazor.Layout\Cheetah.Blazor.Layout.csproj"/>
        <ProjectReference Include="..\Cheetah.Core\Cheetah.Core.csproj"/>
        <ProjectReference Include="..\Cheetah.Frontend.Navigation\Cheetah.Frontend.Navigation.csproj"/>
        <ProjectReference Include="..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer"/>
    </ItemGroup>

</Project>
