<Project Sdk="Microsoft.NET.Sdk">


  <ItemGroup>
    <ProjectReference Include="..\Cheetah.Tenants.Events\Cheetah.Tenants.Events.csproj" />
    <ProjectReference Include="..\..\Cheetah.Core.Domain\Cheetah.Core.Domain.csproj" />
    <ProjectReference Include="..\..\Cheetah.Core\Cheetah.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
  </ItemGroup>

</Project>
