<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\Cheetah.Core.CQRS\Cheetah.Core.CQRS.csproj" />
        <ProjectReference Include="..\..\..\..\Cheetah.Mapping.Core\Cheetah.Mapping.Core.csproj" />
        <ProjectReference Include="..\..\..\..\Cheetah.Core.Grid\Cheetah.Core.Grid.csproj" />
        <ProjectReference Include="..\..\..\..\Cheetah.Core\Cheetah.Core.csproj" />
        <ProjectReference Include="..\..\..\..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
        <ProjectReference Include="..\Crm.VacancyTasks.Contracts\Crm.VacancyTasks.Contracts.csproj" />
        <ProjectReference Include="..\Crm.VacancyTasks.DataAccess\Crm.VacancyTasks.DataAccess.csproj" />
        <ProjectReference Include="..\Crm.VacancyTasks.DomainEvents\Crm.VacancyTasks.DomainEvents.csproj" />
        <ProjectReference Include="..\Crm.VacancyTasks.Domain\Crm.VacancyTasks.Domain.csproj" />
    </ItemGroup>

</Project>
