<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\Cheetah.Core\Cheetah.Core.csproj" />
      <ProjectReference Include="..\Cheetah.Mapping.Core\Cheetah.Mapping.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Mapster" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    </ItemGroup>

</Project>
