// <auto-generated />
using System;
using Cheetah.Modules.Notes.Default.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cheetah.Modules.Notes.Default.Persistence.Migrations
{
    [DbContext(typeof(NotesDbContext))]
    [Migration("20260822102102_InitialNotes")]
    partial class InitialNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cheetah.Modules.Notes.Default.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentFileIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("AttachmentFileIds");

                    b.Property<string>("Attributes")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Mentions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("Mentions");

                    b.Property<Guid?>("ParentNoteId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PinnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ParentNoteId");

                    b.HasIndex("PinnedAt");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("Notes", "notes");
                });
#pragma warning restore 612, 618
        }
    }
}
