syntax = "proto3";

option csharp_namespace = "Crm.Customer.Api.Grpc";

package crm.customer;

// gRPC-фасад модуля Customer. Методы транслируются в CQRS через IDispatcher.
service CustomerGrpc {
  rpc GetCustomerById (GetCustomerByIdGrpcRequest) returns (CustomerGrpcReply);
  rpc CreateCustomer (CreateCustomerGrpcRequest) returns (CreateCustomerGrpcReply);
}

message GetCustomerByIdGrpcRequest {
  string id = 1;
}

message CustomerGrpcReply {
  string id = 1;
  string name = 2;
  optional string description = 3;
  optional string industry_id = 4;
}

message CreateCustomerGrpcRequest {
  string name = 1;
  optional string description = 2;
  optional string industry_id = 3;
}

message CreateCustomerGrpcReply {
  string id = 1;
}
