<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Cheetah.AspNetCore.Contracts\Cheetah.AspNetCore.Contracts.csproj" />
      <ProjectReference Include="..\Cheetah.Contracts\Cheetah.Contracts.csproj" />
      <ProjectReference Include="..\Cheetah.Core.CQRS\Cheetah.Core.CQRS.csproj" />
      <ProjectReference Include="..\Cheetah.Core\Cheetah.Core.csproj" />
      <ProjectReference Include="..\Cheetah.RateLimit\Cheetah.RateLimit.csproj" />
    </ItemGroup>

</Project>
