using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Cheetah.Generators.Grpc;

/// <summary>
/// Генерирует реализации gRPC-сервисов по классам-маркерам (GrpcCommand / GrpcCommandWithResult /
/// GrpcQuery / GrpcQueryOrNotFound). Каждый метод транслируется в вызов <c>IDispatcher</c> —
/// аналогично тому, как <c>EndpointRegistrationGenerator</c> делает для REST.
/// </summary>
[Generator]
public class GrpcServiceGenerator : IIncrementalGenerator
{
    private const string Command = "Cheetah.Backend.Grpc.Abstractions.GrpcCommand`2";
    private const string CommandWithResult = "Cheetah.Backend.Grpc.Abstractions.GrpcCommandWithResult`4";
    private const string Query = "Cheetah.Backend.Grpc.Abstractions.GrpcQuery`4";
    private const string QueryOrNotFound = "Cheetah.Backend.Grpc.Abstractions.GrpcQueryOrNotFound`4";

    private const string ServerCallContextType = "Grpc.Core.ServerCallContext";
    private const string DiagId = "GRPCGEN001";

    private static readonly string[] MarkerBaseTypes = { Command, CommandWithResult, Query, QueryOrNotFound };

    private static readonly SymbolDisplayFormat FqnNullable = SymbolDisplayFormat.FullyQualifiedFormat
        .AddMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var markers = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax c &&
                                               !c.Modifiers.Any(m => m.ValueText == "abstract"),
                transform: static (ctx, _) => GetMarker(ctx))
            .Where(static m => m is not null)
            .Collect();

        var combined = markers.Combine(context.CompilationProvider);

        context.RegisterSourceOutput(combined, static (ctx, pair) =>
            Generate(ctx, pair.Left!, pair.Right));
    }

    private static MarkerInfo? GetMarker(GeneratorSyntaxContext context)
    {
        var symbol = context.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)context.Node) as INamedTypeSymbol;
        if (symbol is null || symbol.IsAbstract)
            return null;

        for (var t = symbol.BaseType; t is not null; t = t.BaseType)
        {
            var name = GenericName(t);
            if (MarkerBaseTypes.Contains(name))
                return new MarkerInfo(symbol, t, name);
        }

        return null;
    }

    private static void Generate(SourceProductionContext ctx, ImmutableArray<MarkerInfo?> markers, Compilation compilation)
    {
        if (markers.IsDefaultOrEmpty)
            return;

        var protoMethods = BuildProtoMethodMap(compilation.Assembly.GlobalNamespace);

        // group markers by proto service base class
        var byBaseClass = new Dictionary<INamedTypeSymbol, List<ResolvedMethod>>(SymbolEqualityComparer.Default);

        foreach (var marker in markers.Where(m => m is not null).Cast<MarkerInfo>())
        {
            var protoRequest = marker.BaseType.TypeArguments[0];

            if (!protoMethods.TryGetValue(protoRequest, out var pm))
            {
                ctx.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(DiagId, "gRPC generator",
                        $"Не найден gRPC-метод proto-базы для запроса '{protoRequest.ToDisplayString()}' (маркер {marker.ClassSymbol.Name}).",
                        "Cheetah.Grpc", DiagnosticSeverity.Warning, true),
                    marker.ClassSymbol.Locations.FirstOrDefault()));
                continue;
            }

            if (!byBaseClass.TryGetValue(pm.BaseClass, out var list))
            {
                list = new List<ResolvedMethod>();
                byBaseClass[pm.BaseClass] = list;
            }

            list.Add(new ResolvedMethod(marker, pm));
        }

        foreach (var kvp in byBaseClass)
            GenerateService(ctx, kvp.Key, kvp.Value);
    }

    private static void GenerateService(SourceProductionContext ctx, INamedTypeSymbol baseClass, List<ResolvedMethod> methods)
    {
        var ns = baseClass.ContainingNamespace.ToDisplayString();
        var serviceName = (baseClass.ContainingType?.Name ?? Trim(baseClass.Name, "Base")) + "Service";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Сгенерированный gRPC-сервис: транслирует proto-вызовы в IDispatcher.</summary>");
        sb.AppendLine($"public sealed class {serviceName} : {baseClass.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly global::Cheetah.Core.CQRS.IDispatcher _dispatcher;");
        sb.AppendLine("    private readonly global::Cheetah.Mapping.Core.IObjectMapper _mapper;");
        sb.AppendLine();
        sb.AppendLine($"    public {serviceName}(global::Cheetah.Core.CQRS.IDispatcher dispatcher, global::Cheetah.Mapping.Core.IObjectMapper mapper)");
        sb.AppendLine("    {");
        sb.AppendLine("        _dispatcher = dispatcher;");
        sb.AppendLine("        _mapper = mapper;");
        sb.AppendLine("    }");

        foreach (var m in methods)
        {
            sb.AppendLine();
            GenerateMethod(sb, m);
        }

        sb.AppendLine("}");

        ctx.AddSource($"{serviceName}.Grpc.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateMethod(StringBuilder sb, ResolvedMethod m)
    {
        var req = m.Proto.RequestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var resp = m.Proto.ResponseType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var methodName = m.Proto.MethodName;
        var args = m.Marker.BaseType.TypeArguments;

        sb.AppendLine($"    public override async global::System.Threading.Tasks.Task<{resp}> {methodName}(");
        sb.AppendLine($"        {req} request, global::Grpc.Core.ServerCallContext context)");
        sb.AppendLine("    {");

        switch (m.Marker.Kind)
        {
            case Command:
            {
                var cmd = args[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine($"        var command = _mapper.Map<{cmd}>(request);");
                sb.AppendLine("        await _dispatcher.SendAsync(command, context.CancellationToken);");
                sb.AppendLine($"        return new {resp}();");
                break;
            }
            case CommandWithResult:
            {
                var cmd = args[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var res = args[2].ToDisplayString(FqnNullable);
                sb.AppendLine($"        var command = _mapper.Map<{cmd}>(request);");
                sb.AppendLine($"        var result = await _dispatcher.SendAsync<{cmd}, {res}>(command, context.CancellationToken);");
                sb.AppendLine($"        return _mapper.Map<{resp}>(result);");
                break;
            }
            case Query:
            {
                var q = args[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var res = args[2].ToDisplayString(FqnNullable);
                sb.AppendLine($"        var query = _mapper.Map<{q}>(request);");
                sb.AppendLine($"        var result = await _dispatcher.QueryAsync<{q}, {res}>(query, context.CancellationToken);");
                sb.AppendLine($"        return _mapper.Map<{resp}>(result);");
                break;
            }
            case QueryOrNotFound:
            {
                var q = args[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var res = args[2].ToDisplayString(FqnNullable);
                sb.AppendLine($"        var query = _mapper.Map<{q}>(request);");
                sb.AppendLine($"        var result = await _dispatcher.QueryAsync<{q}, {res}>(query, context.CancellationToken);");
                sb.AppendLine("        if (result is null)");
                sb.AppendLine("            throw new global::Grpc.Core.RpcException(new global::Grpc.Core.Status(");
                sb.AppendLine($"                global::Grpc.Core.StatusCode.NotFound, \"{methodName}: not found\"));");
                sb.AppendLine($"        return _mapper.Map<{resp}>(result);");
                break;
            }
        }

        sb.AppendLine("    }");
    }

    /// <summary>Собирает карту: тип proto-запроса -> (имя метода, базовый класс сервиса, тип ответа).</summary>
    private static Dictionary<ITypeSymbol, ProtoMethod> BuildProtoMethodMap(INamespaceSymbol root)
    {
        var map = new Dictionary<ITypeSymbol, ProtoMethod>(SymbolEqualityComparer.Default);

        foreach (var type in EnumerateTypes(root))
        {
            foreach (var method in type.GetMembers().OfType<IMethodSymbol>())
            {
                if (!method.IsVirtual || method.Parameters.Length != 2)
                    continue;

                if (method.Parameters[1].Type.ToDisplayString() != ServerCallContextType)
                    continue;

                if (method.ReturnType is not INamedTypeSymbol { Name: "Task", TypeArguments.Length: 1 } ret)
                    continue;

                var requestType = method.Parameters[0].Type;
                if (!map.ContainsKey(requestType))
                    map[requestType] = new ProtoMethod(method.Name, type, requestType, ret.TypeArguments[0]);
            }
        }

        return map;
    }

    private static IEnumerable<INamedTypeSymbol> EnumerateTypes(INamespaceSymbol ns)
    {
        foreach (var type in ns.GetTypeMembers())
        foreach (var t in WithNested(type))
            yield return t;

        foreach (var child in ns.GetNamespaceMembers())
        foreach (var t in EnumerateTypes(child))
            yield return t;
    }

    private static IEnumerable<INamedTypeSymbol> WithNested(INamedTypeSymbol type)
    {
        yield return type;
        foreach (var nested in type.GetTypeMembers())
        foreach (var t in WithNested(nested))
            yield return t;
    }

    private static string GenericName(INamedTypeSymbol type)
    {
        if (!type.IsGenericType)
            return type.ToDisplayString();
        return $"{type.ContainingNamespace.ToDisplayString()}.{type.Name}`{type.TypeArguments.Length}";
    }

    private static string Trim(string value, string suffix) =>
        value.EndsWith(suffix) ? value.Substring(0, value.Length - suffix.Length) : value;

    private sealed record MarkerInfo(INamedTypeSymbol ClassSymbol, INamedTypeSymbol BaseType, string Kind);

    private sealed record ProtoMethod(string MethodName, INamedTypeSymbol BaseClass, ITypeSymbol RequestType, ITypeSymbol ResponseType);

    private sealed record ResolvedMethod(MarkerInfo Marker, ProtoMethod Proto);
}
