using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Cheetah.Generators.Common;

[Generator]
public class SyncHashGenerator : IIncrementalGenerator
{
    private const string SyncHashAttributeName = "Cheetah.Core.Attributes.SyncHashAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var typesProvider = context.CompilationProvider
            .Select(static (compilation, ct) => GetTypesWithSyncHash(compilation, ct));

        context.RegisterSourceOutput(typesProvider, static (ctx, types) =>
        {
            foreach (var typeInfo in types)
                GenerateHashExtensions(ctx, typeInfo);
        });
    }

    private static ImmutableArray<SyncHashTypeInfo> GetTypesWithSyncHash(
        Compilation compilation, System.Threading.CancellationToken ct)
    {
        var results = ImmutableArray.CreateBuilder<SyncHashTypeInfo>();
        SearchNamespace(compilation.Assembly.GlobalNamespace, results, ct);
        return results.ToImmutable();
    }

    private static void SearchNamespace(INamespaceSymbol ns,
        ImmutableArray<SyncHashTypeInfo>.Builder results,
        System.Threading.CancellationToken ct)
    {
        foreach (var type in ns.GetTypeMembers())
        {
            ct.ThrowIfCancellationRequested();
            var hashProps = CollectHashProperties(type);
            if (hashProps.Length > 0)
                results.Add(new SyncHashTypeInfo(type, hashProps));
        }

        foreach (var nested in ns.GetNamespaceMembers())
            SearchNamespace(nested, results, ct);
    }

    private static ImmutableArray<string> CollectHashProperties(INamedTypeSymbol type)
    {
        var props = new List<(string Name, int Order)>();

        // Explicit [SyncHash] on properties
        foreach (var member in type.GetMembers())
        {
            if (member is IPropertySymbol property &&
                TryGetSyncHashOrder(property.GetAttributes(), out var order))
            {
                props.Add((property.Name, order));
            }
        }

        // [SyncHash] on record primary constructor parameters
        foreach (var ctor in type.Constructors)
        {
            foreach (var param in ctor.Parameters)
            {
                if (!TryGetSyncHashOrder(param.GetAttributes(), out var order))
                    continue;

                // PascalCase: first letter upper
                var propName = param.Name.Length > 0
                    ? char.ToUpperInvariant(param.Name[0]) + param.Name.Substring(1)
                    : param.Name;

                if (!props.Exists(p => p.Name == propName))
                    props.Add((propName, order));
            }
        }

        if (props.Count == 0)
            return ImmutableArray<string>.Empty;

        return props
            .OrderBy(p => p.Order)
            .ThenBy(p => p.Name)  // stable secondary sort
            .Select(p => p.Name)
            .ToImmutableArray();
    }

    private static bool TryGetSyncHashOrder(ImmutableArray<AttributeData> attributes, out int order)
    {
        foreach (var attr in attributes)
        {
            if (attr.AttributeClass?.ToDisplayString() != SyncHashAttributeName)
                continue;

            order = attr.ConstructorArguments.Length > 0 &&
                    attr.ConstructorArguments[0].Value is int o ? o : 0;
            return true;
        }

        order = 0;
        return false;
    }

    private static void GenerateHashExtensions(SourceProductionContext ctx, SyncHashTypeInfo typeInfo)
    {
        var typeName = typeInfo.Type.Name;
        var typeFullName = typeInfo.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var ns = typeInfo.Type.ContainingNamespace.IsGlobalNamespace
            ? null
            : typeInfo.Type.ContainingNamespace.ToDisplayString();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine();

        if (ns != null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        sb.AppendLine($"public static class {typeName}HashExtensions");
        sb.AppendLine("{");

        // ComputeHash
        var hashContent = BuildHashContent(typeInfo.HashProperties);
        sb.AppendLine($"    public static string ComputeHash(this {typeFullName} vm) =>");
        sb.AppendLine($"        Hash({hashContent});");
        sb.AppendLine();

        // ComputeBatchHash
        sb.AppendLine($"    public static string ComputeBatchHash(");
        sb.AppendLine($"        this global::System.Collections.Generic.IEnumerable<{typeFullName}> items) =>");
        sb.AppendLine("        Hash(string.Join(\";\",");
        sb.AppendLine($"            items.OrderBy(x => x.Id).Select(x => $\"{{x.Id}}:{{x.ComputeHash()}}\")));");
        sb.AppendLine();

        // Private Hash helper — inlined per extension class to avoid cross-assembly dependency
        sb.AppendLine("    private static string Hash(string input)");
        sb.AppendLine("    {");
        sb.AppendLine("        var bytes = global::System.Security.Cryptography.SHA256.HashData(");
        sb.AppendLine("            global::System.Text.Encoding.UTF8.GetBytes(input));");
        sb.AppendLine("        return global::System.Convert.ToHexString(bytes);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{typeName}HashExtensions.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string BuildHashContent(ImmutableArray<string> props)
    {
        if (props.Length == 1)
            return $"vm.{props[0]}";

        var parts = new StringBuilder();
        for (var i = 0; i < props.Length; i++)
        {
            if (i > 0) parts.Append(", \"\\x1E\", ");
            parts.Append($"vm.{props[i]}");
        }
        return $"string.Concat({parts})";
    }

    private sealed record SyncHashTypeInfo(
        INamedTypeSymbol Type,
        ImmutableArray<string> HashProperties);
}
