using Cheetah.AspNetCore;
using Cheetah.Backend.Endpoints;
using Cheetah.Core.Modularity;
using Cheetah.Mapping.Mapster;
using Cheetah.Tenants.Application;
using Cheetah.Tenants.Contracts;

namespace Cheetah.Tenants.Api;

[DependsOn(typeof(CrmTenantsApplicationModule))]
[DependsOn(typeof(CrmTenantsContractsModule))]
[DependsOn(typeof(CrmAspNetCoreModule))]
[DependsOn(typeof(CrmMapsterModule))]
[DependsOn(typeof(CrmBackendEndpointsModule))]
public partial class CrmTenantsApiModule : CrmModule
{
    public override void ConfigureServices(ServiceConfigurationContext context)
    {
        RegisterServices(context.Services);
    }

    // OnApplicationInitialization will be generated by EndpointRegistrationGenerator
}
