<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Cheetah.Core\Cheetah.Core.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Core.CQRS\Cheetah.Core.CQRS.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Core.DataAccess\Cheetah.Core.DataAccess.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Core.Events\Cheetah.Core.Events.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.BackgroundTasks\Cheetah.BackgroundTasks.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.DistributedLock\Cheetah.DistributedLock.csproj" />
        <ProjectReference Include="..\Cheetah.Modules.Calendar.Domain\Cheetah.Modules.Calendar.Domain.csproj" />
        <ProjectReference Include="..\Cheetah.Modules.Calendar.Contracts\Cheetah.Modules.Calendar.Contracts.csproj" />
        <ProjectReference Include="..\Cheetah.Modules.Calendar.DomainEvents\Cheetah.Modules.Calendar.DomainEvents.csproj" />
        <ProjectReference Include="..\..\Notification\Cheetah.Modules.Notification.DomainEvents\Cheetah.Modules.Notification.DomainEvents.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    </ItemGroup>

</Project>
