<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Cheetah.Core\Cheetah.Core.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Core.CQRS\Cheetah.Core.CQRS.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Core.DataAccess\Cheetah.Core.DataAccess.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Core.Events\Cheetah.Core.Events.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Validation\Cheetah.Validation.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Expressions\Cheetah.Expressions.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Expressions.JsonLogic\Cheetah.Expressions.JsonLogic.csproj" />
        <ProjectReference Include="..\Cheetah.Modules.CustomFields.Domain\Cheetah.Modules.CustomFields.Domain.csproj" />
        <ProjectReference Include="..\Cheetah.Modules.CustomFields.Contracts\Cheetah.Modules.CustomFields.Contracts.csproj" />
        <ProjectReference Include="..\Cheetah.Modules.CustomFields.DomainEvents\Cheetah.Modules.CustomFields.DomainEvents.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    </ItemGroup>

</Project>
