// <auto-generated />
using System;
using Cheetah.Modules.FeatureManagement.Default.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cheetah.Modules.FeatureManagement.Default.Persistence.Migrations
{
    [DbContext(typeof(FeatureManagementDbContext))]
    partial class FeatureManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cheetah.Modules.FeatureManagement.Default.Entities.FeatureFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OwnerService")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ValueType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("OwnerService");

                    b.ToTable("FeatureFlags", "features");
                });

            modelBuilder.Entity("Cheetah.Modules.FeatureManagement.Domain.Entities.FeatureVariantDef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FlagId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FlagId");

                    b.ToTable("FeatureVariants", "features");
                });

            modelBuilder.Entity("Cheetah.Modules.FeatureManagement.Domain.Entities.TargetingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FilterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("FlagId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Negate")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ResultVariant")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("FlagId", "Order");

                    b.ToTable("TargetingRules", "features");
                });

            modelBuilder.Entity("Cheetah.Modules.FeatureManagement.Domain.Entities.TenantOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FlagId")
                        .HasColumnType("uuid");

                    b.Property<string>("RulesJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FlagId", "TenantId")
                        .IsUnique();

                    b.ToTable("TenantOverrides", "features");
                });

            modelBuilder.Entity("Cheetah.Modules.FeatureManagement.Domain.Entities.FeatureVariantDef", b =>
                {
                    b.HasOne("Cheetah.Modules.FeatureManagement.Default.Entities.FeatureFlag", null)
                        .WithMany("Variants")
                        .HasForeignKey("FlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cheetah.Modules.FeatureManagement.Domain.Entities.TargetingRule", b =>
                {
                    b.HasOne("Cheetah.Modules.FeatureManagement.Default.Entities.FeatureFlag", null)
                        .WithMany("Rules")
                        .HasForeignKey("FlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cheetah.Modules.FeatureManagement.Domain.Entities.TenantOverride", b =>
                {
                    b.HasOne("Cheetah.Modules.FeatureManagement.Default.Entities.FeatureFlag", null)
                        .WithMany("Overrides")
                        .HasForeignKey("FlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cheetah.Modules.FeatureManagement.Default.Entities.FeatureFlag", b =>
                {
                    b.Navigation("Overrides");

                    b.Navigation("Rules");

                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
