<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Cheetah.Core\Cheetah.Core.csproj" />
        <ProjectReference Include="..\Cheetah.Contracts\Cheetah.Contracts.csproj" />
        <ProjectReference Include="..\Cheetah.Core.EntityFramework\Cheetah.Core.EntityFramework.csproj" />
        <ProjectReference Include="..\Cheetah.Mapping.Core\Cheetah.Mapping.Core.csproj" />
        <ProjectReference Include="..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    </ItemGroup>

</Project>
