<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Cheetah.Backend.IdentityCore.Domain\Cheetah.Backend.IdentityCore.Domain.csproj" />
    <ProjectReference Include="..\..\Cheetah.Core.Domain\Cheetah.Core.Domain.csproj" />
    <ProjectReference Include="..\Cheetah.Identity.Events\Cheetah.Identity.Events.csproj" />
    <ProjectReference Include="..\..\Cheetah.Core\Cheetah.Core.csproj" />
    <ProjectReference Include="..\..\Cheetah.Core.Specification\Cheetah.Core.Specification.csproj" />
  </ItemGroup>


</Project>
