<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Cheetah.Features.Application\Cheetah.Features.Application.csproj" />
    <ProjectReference Include="..\Cheetah.Features.DataAccess\Cheetah.Features.DataAccess.csproj" />
    <ProjectReference Include="..\Cheetah.Features.Shared\Cheetah.Features.Shared.csproj" />
    <ProjectReference Include="..\..\Cheetah.AspNetCore\Cheetah.AspNetCore.csproj" />
    <ProjectReference Include="..\..\Cheetah.Mapping.Mapster\Cheetah.Mapping.Mapster.csproj" />
    <ProjectReference Include="..\..\Cheetah.Core\Cheetah.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
  </ItemGroup>

</Project>
