using System.Linq.Expressions;
using System.Reflection;

namespace Cheetah.Core.Dapper.Mapping;

/// <summary>
/// Fluent base class for declaring how an entity maps to a table — the Dapper
/// counterpart of EF Core's <c>IEntityTypeConfiguration&lt;T&gt;</c>.
/// Derive, configure in the constructor, and the type is auto-registered.
/// </summary>
/// <typeparam name="TEntity">The entity type being mapped.</typeparam>
/// <example>
/// <code>
/// public sealed class CustomerMap : DapperEntityMap&lt;Customer&gt;
/// {
///     public CustomerMap()
///     {
///         ToTable("Customers", schema: "crm");
///         HasKey(x => x.Id);                 // database-generated by default for non-Guid keys
///         Column(x => x.FullName, "full_name");
///         Ignore(x => x.TemporaryFlag);
///     }
/// }
/// </code>
/// </example>
public abstract class DapperEntityMap<TEntity> : IDapperEntityMap<TEntity>
    where TEntity : class
{
    private string? _tableName;
    private string? _schema;
    private PropertyInfo? _keyProperty;
    private bool? _keyDatabaseGenerated;
    private readonly Dictionary<string, string> _columnNames = new();
    private readonly HashSet<string> _ignored = new();
    private readonly HashSet<string> _databaseGenerated = new();

    /// <inheritdoc />
    public Type EntityType => typeof(TEntity);

    /// <summary>Sets the table (and optional schema) name.</summary>
    protected void ToTable(string tableName, string? schema = null)
    {
        _tableName = tableName;
        _schema = schema;
    }

    /// <summary>Declares the primary-key property.</summary>
    /// <param name="keySelector">Property selector, e.g. <c>x =&gt; x.Id</c>.</param>
    /// <param name="databaseGenerated">
    /// Whether the key is produced by the database. When <c>null</c> (default) it is inferred:
    /// <see cref="Guid"/> keys are treated as application-assigned, all others as database-generated.
    /// </param>
    protected void HasKey<TKey>(Expression<Func<TEntity, TKey>> keySelector, bool? databaseGenerated = null)
    {
        _keyProperty = GetProperty(keySelector);
        _keyDatabaseGenerated = databaseGenerated;
    }

    /// <summary>Overrides the column name for a property.</summary>
    protected void Column<TProp>(Expression<Func<TEntity, TProp>> selector, string columnName)
        => _columnNames[GetProperty(selector).Name] = columnName;

    /// <summary>Excludes a property from mapping.</summary>
    protected void Ignore<TProp>(Expression<Func<TEntity, TProp>> selector)
        => _ignored.Add(GetProperty(selector).Name);

    /// <summary>Marks a non-key property as database-generated (excluded from INSERT/UPDATE).</summary>
    protected void DatabaseGenerated<TProp>(Expression<Func<TEntity, TProp>> selector)
        => _databaseGenerated.Add(GetProperty(selector).Name);

    /// <inheritdoc />
    public EntityMapping Build()
    {
        var keyProperty = _keyProperty ?? typeof(TEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance)
            ?? throw new InvalidOperationException(
                $"Entity '{typeof(TEntity).Name}' has no 'Id' property; call HasKey(...) in its map.");

        var keyGenerated = _keyDatabaseGenerated ?? keyProperty.PropertyType != typeof(Guid);

        var columns = new List<ColumnMapping>();
        foreach (var property in MappingConventions.GetMappableProperties(typeof(TEntity)))
        {
            if (_ignored.Contains(property.Name))
                continue;

            var isKey = property.Name == keyProperty.Name;
            columns.Add(new ColumnMapping
            {
                Property = property,
                ColumnName = _columnNames.GetValueOrDefault(property.Name, property.Name),
                IsKey = isKey,
                IsDatabaseGenerated = (isKey && keyGenerated) || _databaseGenerated.Contains(property.Name),
            });
        }

        var key = columns.FirstOrDefault(c => c.IsKey)
            ?? throw new InvalidOperationException(
                $"Key property '{keyProperty.Name}' of '{typeof(TEntity).Name}' is not mappable.");

        return new EntityMapping
        {
            EntityType = typeof(TEntity),
            TableName = _tableName ?? MappingConventions.GetTableName(typeof(TEntity)),
            Schema = _schema,
            Key = key,
            Columns = columns,
        };
    }

    private static PropertyInfo GetProperty<TProp>(Expression<Func<TEntity, TProp>> selector)
    {
        var body = selector.Body as MemberExpression
                   ?? (selector.Body as UnaryExpression)?.Operand as MemberExpression;

        if (body?.Member is PropertyInfo property)
            return property;

        throw new ArgumentException($"Expression '{selector}' does not refer to a property.", nameof(selector));
    }
}
