<Project Sdk="Microsoft.NET.Sdk">

   

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="$(MsPackageVersion)" />
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="$(MsPackageVersion)" />
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="$(MsPackageVersion)" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="$(MsPackageVersion)" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="$(MsPackageVersion)" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="$(MsPackageVersion)" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="$(MsPackageVersion)" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="$(MsPackageVersion)" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="$(MsPackageVersion)" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="$(MsPackageVersion)" />
    </ItemGroup>

</Project>
