<Project Sdk="Microsoft.NET.Sdk">


  <ItemGroup>
    <ProjectReference Include="..\Cheetah.Tenants.Events\Cheetah.Tenants.Events.csproj" />
    <ProjectReference Include="..\Cheetah.Tenants.Domain\Cheetah.Tenants.Domain.csproj" />
    <ProjectReference Include="..\Cheetah.Tenants.DataAccess\Cheetah.Tenants.DataAccess.csproj" />
    <ProjectReference Include="..\..\Cheetah.Core.CQRS\Cheetah.Core.CQRS.csproj" />
    <ProjectReference Include="..\..\Cheetah.Core.Events\Cheetah.Core.Events.csproj" />
    <ProjectReference Include="..\..\Cheetah.Core.DataAccess\Cheetah.Core.DataAccess.csproj" />
    <ProjectReference Include="..\..\Cheetah.Core\Cheetah.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
  </ItemGroup>

</Project>
