<Project Sdk="Microsoft.NET.Sdk">
    

    <ItemGroup>
        <ProjectReference Include="..\..\..\Cheetah.Core\Cheetah.Core.csproj"/>
        <ProjectReference Include="..\..\..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer"/>
        <ProjectReference Include="..\Crm.Features.Contracts\Crm.Features.Contracts.csproj" />
        <ProjectReference Include="..\Crm.Features.DataAccess\Crm.Features.DataAccess.csproj" />
        <ProjectReference Include="..\Crm.Features.DomainEvents\Crm.Features.DomainEvents.csproj" />
        <ProjectReference Include="..\Crm.Features.Domain\Crm.Features.Domain.csproj" />
    </ItemGroup>

</Project>
