<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\..\Cheetah.Core\Cheetah.Core.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Core.Domain\Cheetah.Core.Domain.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Core.Specification\Cheetah.Core.Specification.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj"
                          ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
        <ProjectReference Include="..\Cheetah.Modules.Tags.Shared\Cheetah.Modules.Tags.Shared.csproj" />
        <ProjectReference Include="..\Cheetah.Modules.Tags.DomainEvents\Cheetah.Modules.Tags.DomainEvents.csproj" />
    </ItemGroup>

</Project>
