<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="$(MsPackageVersion)"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Cheetah.AspNetCore\Cheetah.AspNetCore.csproj" />
      <ProjectReference Include="..\Cheetah.Core\Cheetah.Core.csproj" />
      <ProjectReference Include="..\Cheetah.Generators.Application\Cheetah.Generators.Application.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer"/>
      <ProjectReference Include="..\Cheetah.Mapping.Mapster\Cheetah.Mapping.Mapster.csproj" />
      <ProjectReference Include="..\Cheetah.OpenApi\Cheetah.OpenApi.csproj" />
      <ProjectReference Include="..\Cheetah.Scalar\Cheetah.Scalar.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer"/>
    </ItemGroup>

</Project>
