<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Cheetah.Features.Shared\Cheetah.Features.Shared.csproj" />
    <ProjectReference Include="..\Cheetah.Features.Application\Cheetah.Features.Application.csproj" />
    <ProjectReference Include="..\..\Cheetah.Core.CQRS\Cheetah.Core.CQRS.csproj" />
    <ProjectReference Include="..\..\Cheetah.Core\Cheetah.Core.csproj" />
    <ProjectReference Include="..\..\Cheetah.Core.Tenants\Cheetah.Core.Tenants.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
  </ItemGroup>

</Project>
