<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\Cheetah.AspNetCore\Cheetah.AspNetCore.csproj" />
      <ProjectReference Include="..\Cheetah.Core\Cheetah.Core.csproj" />
      <ProjectReference Include="..\Cheetah.OpenApi\Cheetah.OpenApi.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Scalar.AspNetCore" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    </ItemGroup>

</Project>
