<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Cheetah.Core\Cheetah.Core.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Core.CQRS\Cheetah.Core.CQRS.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Core.DataAccess\Cheetah.Core.DataAccess.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Core.Events\Cheetah.Core.Events.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Core.Grid\Cheetah.Core.Grid.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Core.StateMachine\Cheetah.Core.StateMachine.csproj" />
        <ProjectReference Include="..\Cheetah.Modules.SalesDocuments.Domain\Cheetah.Modules.SalesDocuments.Domain.csproj" />
        <ProjectReference Include="..\Cheetah.Modules.SalesDocuments.Contracts\Cheetah.Modules.SalesDocuments.Contracts.csproj" />
        <ProjectReference Include="..\Cheetah.Modules.SalesDocuments.DomainEvents\Cheetah.Modules.SalesDocuments.DomainEvents.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    </ItemGroup>

</Project>
