<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\..\Cheetah.Core.Domain\Cheetah.Core.Domain.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Core.Identity.Domain\Cheetah.Core.Identity.Domain.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Core\Cheetah.Core.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj"
                          ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
        <ProjectReference Include="..\Cheetah.Modules.Identity.DomainEvents\Cheetah.Modules.Identity.DomainEvents.csproj" />
    </ItemGroup>

</Project>
