using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Cheetah.Mapping.Generators;

[Generator]
public class MappingGenerator : IIncrementalGenerator
{
    private const string MapFromAttributeName = "Cheetah.Mapping.Core.MapFromAttribute";
    private const string MapIgnoreAttributeName = "Cheetah.Mapping.Core.MapIgnoreAttribute";
    private const string MapPropertyAttributeName = "Cheetah.Mapping.Core.MapPropertyAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (s, _) => s is ClassDeclarationSyntax c && c.AttributeLists.Count > 0,
                transform: GetClassWithMapFromAttribute)
            .Where(t => t != null);

        var compilationAndClasses = context.CompilationProvider.Combine(provider.Collect());

        context.RegisterSourceOutput(compilationAndClasses,
            (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private INamedTypeSymbol? GetClassWithMapFromAttribute(GeneratorSyntaxContext context, System.Threading.CancellationToken ct)
    {
        var classSyntax = (ClassDeclarationSyntax)context.Node;
        var typeSymbol = context.SemanticModel.GetDeclaredSymbol(classSyntax, ct) as INamedTypeSymbol;
        
        if (typeSymbol == null) return null;

        var mapFromAttr = typeSymbol.GetAttributes().FirstOrDefault(a => 
            a.AttributeClass?.ToDisplayString() == MapFromAttributeName);

        if (mapFromAttr != null) return typeSymbol;

        return null;
    }

    private void Execute(Compilation compilation, IEnumerable<INamedTypeSymbol> classes, SourceProductionContext context)
    {
        if (!classes.Any()) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine();
        sb.AppendLine("namespace Cheetah.Mapping.Generated;");
        sb.AppendLine();
        sb.AppendLine("public static class MapperExtensions");
        sb.AppendLine("{");

        foreach (var destClass in classes.Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default))
        {
            var mapFromAttr = destClass.GetAttributes().First(a => a.AttributeClass?.ToDisplayString() == MapFromAttributeName);
            var sourceTypeObj = mapFromAttr.ConstructorArguments.FirstOrDefault().Value;
            
            if (sourceTypeObj is not INamedTypeSymbol sourceClass) continue;

            var destProps = destClass.GetMembers().OfType<IPropertySymbol>().Where(p => !p.IsReadOnly).ToList();
            var sourceProps = sourceClass.GetMembers().OfType<IPropertySymbol>().ToList();

            sb.AppendLine($"    // Mapping from {sourceClass.Name} to {destClass.Name}");
            sb.AppendLine($"    public static {destClass.ToDisplayString()} MapTo{destClass.Name}(this {sourceClass.ToDisplayString()} source)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (source == null) return null;");
            sb.AppendLine($"        return new {destClass.ToDisplayString()}");
            sb.AppendLine("        {");

            var selectLines = new List<string>();

            foreach (var destProp in destProps)
            {
                // Check Ignore
                if (destProp.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == MapIgnoreAttributeName))
                    continue;

                // Check Custom MapProperty
                var mapPropAttr = destProp.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == MapPropertyAttributeName);
                string sourcePropName = destProp.Name;

                if (mapPropAttr != null && mapPropAttr.ConstructorArguments.Length > 0)
                {
                    sourcePropName = (string)mapPropAttr.ConstructorArguments[0].Value!;
                }

                var sourceProp = sourceProps.FirstOrDefault(p => p.Name == sourcePropName);

                if (sourceProp == null)
                {
                    // Валидация: Свойство не найдено в Source и не помечено Ignore! Кидаем Diagnostic Error.
                    var diagnostic = Diagnostic.Create(
                        new DiagnosticDescriptor(
                            id: "CHMAP01",
                            title: "Unmapped Property",
                            messageFormat: "Property '{0}' in destination '{1}' is not mapped to any source property in '{2}'. Use [MapIgnore] or [MapProperty] to resolve.",
                            category: "Mapping",
                            DiagnosticSeverity.Error,
                            isEnabledByDefault: true),
                        destProp.Locations.FirstOrDefault(),
                        destProp.Name, destClass.Name, sourceClass.Name);
                        
                    context.ReportDiagnostic(diagnostic);
                    continue;
                }

                // В реальном проекте тут нужно обрабатывать типы (ToString(), приведение типов). 
                // Пока делаем простое присвоение
                sb.AppendLine($"            {destProp.Name} = source.{sourceProp.Name},");
                selectLines.Add($"{destProp.Name} = x.{sourceProp.Name}");
            }

            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Генерация IQueryable.ProjectTo
            sb.AppendLine($"    public static IQueryable<{destClass.ToDisplayString()}> ProjectTo{destClass.Name}(this IQueryable<{sourceClass.ToDisplayString()}> query)");
            sb.AppendLine("    {");
            sb.AppendLine($"        return query.Select(x => new {destClass.ToDisplayString()}");
            sb.AppendLine("        {");
            foreach (var line in selectLines)
            {
                sb.AppendLine($"            {line},");
            }
            sb.AppendLine("        });");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        context.AddSource("CheetahMappingExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
