<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Cheetah.AspNetCore\Cheetah.AspNetCore.csproj" />
        <ProjectReference Include="..\Cheetah.Backend.Jwt.Abstractions\Cheetah.Backend.Jwt.Abstractions.csproj" />
        <ProjectReference Include="..\Cheetah.Core\Cheetah.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Cheetah.Generators.Module\Cheetah.Generators.Module.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer"/>
    </ItemGroup>

</Project>
