<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Cheetah.Modules.Identity.Application" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\AppName.Identity.Domain\AppName.Identity.Domain.csproj" />
    </ItemGroup>

    <ItemGroup Label="Source Generators">
        <PackageReference Include="Cheetah.Generators.Module">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
