<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\..\Cheetah.Contracts\Cheetah.Contracts.csproj" />
        <ProjectReference Include="..\..\..\Cheetah.Core\Cheetah.Core.csproj" />
        <ProjectReference Include="..\Cheetah.Modules.Tags.Shared\Cheetah.Modules.Tags.Shared.csproj" />
    </ItemGroup>

</Project>
